name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v6


  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        lint-and-coverage: [false]
        include:
          - go-version: 1.22.x
            lint-and-coverage: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: |
          go version
          if [ ${{ matrix.lint-and-coverage }} = true ]; then
              GO_TEST_OPTS="-covermode=atomic -coverprofile=coverage.out"
          fi
          export GORACE="halt_on_error=1"
          go test -race $GO_TEST_OPTS ./...

      - name: Reporting coverage
        if: matrix.lint-and-coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out